
version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql2
    environment:
      - MYSQL_DATABASE=wallet
      - MYSQL_USER=uu
      - MYSQL_PASSWORD=root123!
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
  app-backend:
    image: app-backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql2:3306/wallet?useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=uu
      - spring.datasource.password=root123!
    links:
      - mysql